name: fwdpy_docs

channels:
    - defaults
    - conda-forge

dependencies:
    - python>=3.7
    - sphinx_rtd_theme
    - pybind11>=2.4.3
    - gsl
    - attrs
    - msprime
    - openblas
    - numpy
    - sparse
    - setuptools_scm
    - sphinx-issues
    - ipython
    - cmake
    - black
