name: fwdpy_docs

channels:
    - defaults
    - conda-forge
    - bioconda

dependencies:
    - python>=3.6
    - sphinx_rtd_theme
    - pybind11>=2.4.3
    - gsl==2.4
    - msprime
    - openblas
    - numpy
    - sparse
    - pandas
    - matplotlib
    - ipython
    - cmake
    - pip
    - pip:
        - cppimport
