name: fwdpy_docs

channels:
    - conda-forge
    - defaults
    - r
    - bioconda

dependencies:
    - python==3.5
    - sphinx_rtd_theme==0.1.9
    - gsl
    - doxygen
    - pip:
        - numpy
        - breathe

script:
    - doxygen fwdpy.doxygen
    - doxygen fwdpp.doxygen
